### PR TITLE
Melinda

### PR DESCRIPTION
**Pull request by mel-d**

### CODE REVIEW

**Comment by mel-d** [comment]
The error I'm getting:
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.

**Comment by sumeetjain** [comment]
If things are otherwise working fine, move on. Is this preventing console.log from actually working?

**Comment by mel-d** [comment]
Yes, nothing from my .js file is appearing at all.

**Comment by sumeetjain** [comment]
Hm. I'm not getting any error. I'm looking at Assignment 6. Is that correct?

**Comment by mel-d** [comment]
Yes, 6A specifically.

**Comment by mel-d** [comment]
I just found out that the 'logging' option in my controller was turned off (didn't even know that was a thing...) so that's why none of the console.logs were showing up. Sorry. At least I'll know to check that next time.

**Pull request closed without merging**
